build_script:
  - ps: 'cd senrenbanka.murasame.qqbot; .\build.bat'
  - ps: '7z a QQBot.zip bin\**\*'

image: Visual Studio 2019
configuration: Release
test: off

#---------------------------------#
#  Build Cache                    #
#---------------------------------#

artifacts:
- path: senrenbanka.murasame.qqbot\QQBot.zip
  name: QQBot
