after_build:
  - ps: 'cd senrenbanka.murasame.qqbot; .\build.bat ; 7z a QQBot.zip bin\**\*'

build:
  parallel: true
  project: senrenbanka.murasame.qqbot.sln

image: Visual Studio 2019
configuration: Release
test: off

#---------------------------------#
#  Build Cache                    #
#---------------------------------#

cache:
- packages -> **\packages.config

artifacts:
- path: senrenbanka.murasame.qqbot\QQBot.zip
  name: QQBot
